server:
  port: 8081

spring:
  application:
    name: player-service
  datasource:
    url: jdbc:mysql://localhost:3306/motus_players?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always                # execute data.sql apres init du schema (idempotent, cf. INSERT IGNORE)

logging:
  level:
    fr.dauphine.miageif.motus.player: DEBUG
